<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Daftar;

class DaftarSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        $userData = [
            [
                'full_name' => 'Andi Wijaya',
                'place_of_birth' => 'Jakarta',
                'date_of_birth' => '1990-01-01',
                'address' => 'Jl. Merdeka No. 123',
                'gender' => 'Laki-laki',
                'phone_number' => '08123456789',
                'status' => 'Pekerja',
                'company_name' => 'PT Maju Jaya',
                'company_phone' => '02112345678',
                'email' => 'andi.wijaya@example.com',
                'class' => 'Kelas A',
                'day_time' => 'Senin 08.00',
                'file' => 'daftar/1234567890-example.pdf',
            ],
            [
                'full_name' => 'Budi Santoso',
                'place_of_birth' => 'Surabaya',
                'date_of_birth' => '1995-05-15',
                'address' => 'Jl. Kenanga No. 456',
                'gender' => 'Laki-laki',
                'phone_number' => '0876543210',
                'status' => 'Siswa',
                'company_name' => null,
                'company_phone' => null,
                'email' => 'budi.santoso@example.com',
                'class' => 'Kelas B',
                'day_time' => 'Rabu 10.00',
                'file' => 'daftar/0987654321-sample.pdf',
            ],
            [
                'full_name' => 'Citra Lestari',
                'place_of_birth' => 'Bandung',
                'date_of_birth' => '1992-08-20',
                'address' => 'Jl. Anggrek No. 789',
                'gender' => 'Perempuan',
                'phone_number' => '0856789012',
                'status' => 'Pekerja',
                'company_name' => 'PT Angkasa Raya',
                'company_phone' => '0229876543',
                'email' => 'citra.lestari@example.com',
                'class' => 'Kelas C',
                'day_time' => 'Kamis 14.00',
                'file' => 'daftar/5678901234-test.pdf',
            ],
            [
                'full_name' => 'Dewi Kurniawan',
                'place_of_birth' => 'Yogyakarta',
                'date_of_birth' => '1998-04-12',
                'address' => 'Jl. Melati No. 321',
                'gender' => 'Perempuan',
                'phone_number' => '0812345678',
                'status' => 'Siswa',
                'company_name' => null,
                'company_phone' => null,
                'email' => 'dewi.kurniawan@example.com',
                'class' => 'Kelas D',
                'day_time' => 'Selasa 09.00',
                'file' => 'daftar/4321098765-example.pdf',
            ],
            [
                'full_name' => 'Eko Prasetyo',
                'place_of_birth' => 'Bali',
                'date_of_birth' => '1993-03-23',
                'address' => 'Jl. Sunset Road No. 12',
                'gender' => 'Laki-laki',
                'phone_number' => '08234567890',
                'status' => 'Pekerja',
                'company_name' => 'PT Bali Indah',
                'company_phone' => '0361123456',
                'email' => 'eko.prasetyo@example.com',
                'class' => 'Kelas E',
                'day_time' => 'Jumat 11.00',
                'file' => 'daftar/1234567890-sample.pdf',
            ],
            [
                'full_name' => 'Fitri Aulia',
                'place_of_birth' => 'Semarang',
                'date_of_birth' => '1991-06-30',
                'address' => 'Jl. Durian No. 45',
                'gender' => 'Perempuan',
                'phone_number' => '08123456789',
                'status' => 'Siswa',
                'company_name' => null,
                'company_phone' => null,
                'email' => 'fitri.aulia@example.com',
                'class' => 'Kelas F',
                'day_time' => 'Senin 13.00',
                'file' => 'daftar/2345678901-sample.pdf',
            ],
            [
                'full_name' => 'Gilang Ramadhan',
                'place_of_birth' => 'Makassar',
                'date_of_birth' => '1994-11-11',
                'address' => 'Jl. Kemangi No. 123',
                'gender' => 'Laki-laki',
                'phone_number' => '08234567890',
                'status' => 'Pekerja',
                'company_name' => 'PT Makassar Sejahtera',
                'company_phone' => '0411123456',
                'email' => 'gilang.ramadhan@example.com',
                'class' => 'Kelas G',
                'day_time' => 'Rabu 15.00',
                'file' => 'daftar/3456789012-sample.pdf',
            ],
            [
                'full_name' => 'Hana Rizky',
                'place_of_birth' => 'Medan',
                'date_of_birth' => '1996-02-02',
                'address' => 'Jl. Mawar No. 789',
                'gender' => 'Perempuan',
                'phone_number' => '08123456789',
                'status' => 'Siswa',
                'company_name' => null,
                'company_phone' => null,
                'email' => 'hana.rizky@example.com',
                'class' => 'Kelas H',
                'day_time' => 'Kamis 10.00',
                'file' => 'daftar/4567890123-sample.pdf',
            ],
            [
                'full_name' => 'Iman Syahputra',
                'place_of_birth' => 'Palembang',
                'date_of_birth' => '1997-09-09',
                'address' => 'Jl. Cendana No. 321',
                'gender' => 'Laki-laki',
                'phone_number' => '08234567890',
                'status' => 'Pekerja',
                'company_name' => 'PT Sumatera Makmur',
                'company_phone' => '0711123456',
                'email' => 'iman.syahputra@example.com',
                'class' => 'Kelas I',
                'day_time' => 'Jumat 16.00',
                'file' => 'daftar/5678901234-sample.pdf',
            ],
            [
                'full_name' => 'Joko Susanto',
                'place_of_birth' => 'Surabaya',
                'date_of_birth' => '1998-12-12',
                'address' => 'Jl. Pahlawan No. 45',
                'gender' => 'Laki-laki',
                'phone_number' => '08123456789',
                'status' => 'Siswa',
                'company_name' => null,
                'company_phone' => null,
                'email' => 'joko.susanto@example.com',
                'class' => 'Kelas J',
                'day_time' => 'Senin 08.00',
                'file' => 'daftar/6789012345-sample.pdf',
            ],
            [
                'full_name' => 'Kartika Sari',
                'place_of_birth' => 'Malang',
                'date_of_birth' => '1995-07-07',
                'address' => 'Jl. Kenangan No. 789',
                'gender' => 'Perempuan',
                'phone_number' => '08234567890',
                'status' => 'Siswa',
                'company_name' => null,
                'company_phone' => null,
                'email' => 'kartika.sari@example.com',
                'class' => 'Kelas K',
                'day_time' => 'Selasa 09.00',
                'file' => 'daftar/7890123456-sample.pdf',
            ],
            [
                'full_name' => 'Lukman Hakim',
                'place_of_birth' => 'Padang',
                'date_of_birth' => '1999-04-04',
                'address' => 'Jl. Sawah No. 12',
                'gender' => 'Laki-laki',
                'phone_number' => '08123456789',
                'status' => 'Pekerja',
                'company_name' => 'PT Padang Sejahtera',
                'company_phone' => '0751123456',
                'email' => 'lukman.hakim@example.com',
                'class' => 'Kelas L',
                'day_time' => 'Rabu 10.00',
                'file' => 'daftar/8901234567-sample.pdf',
            ],
            [
                'full_name' => 'Maya Sari',
                'place_of_birth' => 'Denpasar',
                'date_of_birth' => '1993-03-03',
                'address' => 'Jl. Pantai No. 123',
                'gender' => 'Perempuan',
                'phone_number' => '08234567890',
                'status' => 'Siswa',
                'company_name' => null,
                'company_phone' => null,
                'email' => 'maya.sari@example.com',
                'class' => 'Kelas M',
                'day_time' => 'Kamis 11.00',
                'file' => 'daftar/9012345678-sample.pdf',
            ],
            [
                'full_name' => 'Nina Utami',
                'place_of_birth' => 'Samarinda',
                'date_of_birth' => '1994-01-01',
                'address' => 'Jl. Kalimantan No. 456',
                'gender' => 'Perempuan',
                'phone_number' => '08123456789',
                'status' => 'Pekerja',
                'company_name' => 'PT Kalimantan Jaya',
                'company_phone' => '0541123456',
                'email' => 'nina.utami@example.com',
                'class' => 'Kelas N',
                'day_time' => 'Jumat 13.00',
                'file' => 'daftar/1234567891-sample.pdf',
            ],
            [
                'full_name' => 'Oka Suryana',
                'place_of_birth' => 'Pontianak',
                'date_of_birth' => '1995-02-02',
                'address' => 'Jl. Mahakam No. 789',
                'gender' => 'Laki-laki',
                'phone_number' => '08234567890',
                'status' => 'Pekerja',
                'company_name' => 'PT Kalbar Makmur',
                'company_phone' => '0561123456',
                'email' => 'oka.suryana@example.com',
                'class' => 'Kelas O',
                'day_time' => 'Senin 14.00',
                'file' => 'daftar/2345678912-sample.pdf',
            ],
            [
                'full_name' => 'Putri Anggraeni',
                'place_of_birth' => 'Palembang',
                'date_of_birth' => '1996-06-06',
                'address' => 'Jl. Ampera No. 321',
                'gender' => 'Perempuan',
                'phone_number' => '08123456789',
                'status' => 'Siswa',
                'company_name' => null,
                'company_phone' => null,
                'email' => 'putri.anggraeni@example.com',
                'class' => 'Kelas P',
                'day_time' => 'Selasa 10.00',
                'file' => 'daftar/3456789123-sample.pdf',
            ],
            [
                'full_name' => 'Rizky Maulana',
                'place_of_birth' => 'Bandung',
                'date_of_birth' => '1997-07-07',
                'address' => 'Jl. Siliwangi No. 45',
                'gender' => 'Laki-laki',
                'phone_number' => '08234567890',
                'status' => 'Pekerja',
                'company_name' => 'PT Bandung Baru',
                'company_phone' => '0221234567',
                'email' => 'rizky.maulana@example.com',
                'class' => 'Kelas Q',
                'day_time' => 'Rabu 11.00',
                'file' => 'daftar/4567891234-sample.pdf',
            ],
        ];

        foreach ($userData as $user) {
            // Simpan data ke database
            $daftar = new Daftar();
            $daftar->fill($user);
            
            // Simpan file jika ada
            if (isset($user['file'])) {
                // Misalkan file sudah ada dalam storage
                $daftar->file = $user['file'];
            }

            $daftar->save();
        }
    }
}
